### ISSUE TITLE
Why is that?

### ISSUE THREAD

**Issue by wangser10032** [Peyman-Bi/SAttLE#5]
(od) C:\Users\zisui\Downloads\SAttLE-main>python main.py -d fb15k-237 --gpu 0 --batch-size 2048 --evaluate-every 250 --n-epochs 1500 --lr 0.001 --lr-decay 0.995 --lr-step-decay 2 --n-layers 1 --d-embed 100 --num-head 64 --d-k 32 --d-v 50 --d-model 100 --d-inner 2048 --start-test-at 1000 --save-epochs 1100 --dr-enc 0.4 --dr-pff 0.2 --dr-sdp 0.1 --dr-mha 0.3 --decoder twomult
2024-05-06,10:49:29 [INFO] Namespace(gpu=0, lr=0.001, lr_decay=0.995, n_layers=1, n_epochs=1500, dataset='fb15k-237', batch_size=2048, evaluate_every=250, start_test_at=1000, lr_step_decay=2, save_epochs=1100, num_heads=64, d_k=32, d_v=50, d_model=100, d_embed=100, d_inner=2048, label_smoothing=0.1, dr_enc=0.4, dr_pff=0.2, dr_sdp=0.1, dr_mha=0.3, decay_until=1050, decoder='twomult')
True
False
False
2024-05-06,10:49:33 [INFO] train shape: (544230, 3), valid shape: (17535, 3), test shape: (20466, 3)
2024-05-06,10:49:33 [INFO] num entities: 14541, num relations: 237
2024-05-06,10:49:35 [INFO] start training...
Traceback (most recent call last):
  File "C:\Users\zisui\Downloads\SAttLE-main\main.py", line 211, in <module>
    main(args)
  File "C:\Users\zisui\Downloads\SAttLE-main\main.py", line 126, in main
    loss = model.cal_loss(scores, edges)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zisui\Downloads\SAttLE-main\model.py", line 207, in cal_loss
    labels.scatter_(1, edges[:, 2][:, None], 1.)
RuntimeError: scatter(): Expected dtype int64 for index

**Comment by pbaghershahi** [comment]
Hi, I just ran the code with the same command in your comment and it works fine. For pytorch >= 1.0.1 it should work fine and I'm using pytorch == "2.2.1+cu121". 
As I see in your error, the problem is with the dtype of edges matrix is not int64. Could you please check if you are changing the type of edges anywhere. Also you can change the line to:

`labels.scatter_(1, edges[:, 2][:, None].long(), 1.)`

I hope it solves your issue.

**Comment by wangser10032** [comment]
Thank you very much for your reply, I have successfully run your code!
